# Generated by Django 5.1.1 on 2024-11-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0002_remove_visit_hall'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeServiceHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_halls', to='volgtekapp.employee')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_halls', to='volgtekapp.hall')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_halls', to='volgtekapp.service')),
            ],
            options={
                'unique_together': {('employee', 'service')},
            },
        ),
    ]
