# Generated by Django 5.1.1 on 2024-11-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0003_employeeservicehall'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='volgtekapp.hall'),
        ),
        migrations.CreateModel(
            name='ServiceHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volgtekapp.hall')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volgtekapp.service')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='service_halls',
            field=models.ManyToManyField(related_name='employees', to='volgtekapp.servicehall'),
        ),
        migrations.DeleteModel(
            name='EmployeeServiceHall',
        ),
    ]
