# Generated by Django 5.1.1 on 2024-11-27 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0004_visit_hall_servicehall_employee_service_halls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='date_time',
        ),
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 27, 22, 10, 4, 565865, tzinfo=datetime.timezone.utc)),
        ),
    ]
