# Generated by Django 5.1.1 on 2024-11-27 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0005_remove_visit_date_time_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='time',
            field=models.TimeField(default=datetime.time(1, 38, 38, 373279)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 1, 38, 38, 372767)),
        ),
    ]
