# Generated by Django 5.1.1 on 2024-11-28 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0007_remove_hall_opening_hours_hall_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 23, 20, 55, 525964)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.TimeField(default=datetime.time(23, 20, 55, 525963)),
        ),
    ]
