# Generated by Django 5.1.1 on 2024-11-28 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0009_alter_visit_date_alter_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
