# Generated by Django 5.1.1 on 2024-11-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0010_alter_visit_date_alter_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='services',
            field=models.ManyToManyField(related_name='halls', to='volgtekapp.service'),
        ),
    ]
