# Generated by Django 5.1.1 on 2024-11-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0011_hall_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='services',
        ),
    ]
