# Generated by Django 5.1.1 on 2024-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0013_alter_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.CharField(choices=[], max_length=5),
        ),
    ]
