# Generated by Django 5.1.1 on 2024-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0014_alter_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hall',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
