# Generated by Django 5.1.1 on 2024-11-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0015_alter_hall_end_time_alter_hall_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.TimeField(),
        ),
    ]
