# Generated by Django 5.1.1 on 2024-11-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volgtekapp', '0016_alter_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='time',
            field=models.TimeField(),
        ),
    ]
